language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: f681654b5a56451a2c1a596eb3e2705d37c2090a
 local_dir: dist
 on:
   branch: master